// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGtiJlqYkcIqli3NKA8HLa1s5vYTadulQ',
    appId: '1:987636562974:web:5ec32dfbfab1691000820f',
    messagingSenderId: '987636562974',
    projectId: 'indiscipleship-cb71a',
    authDomain: 'indiscipleship-cb71a.firebaseapp.com',
    storageBucket: 'indiscipleship-cb71a.firebasestorage.app',
    measurementId: 'G-S772KYDS54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlQ5f2dU5scJLpk735Z_RoNv22Lyf3C7o',
    appId: '1:987636562974:android:da93d57bd5003b7800820f',
    messagingSenderId: '987636562974',
    projectId: 'indiscipleship-cb71a',
    storageBucket: 'indiscipleship-cb71a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaoqchZaREnHPvsbbIsGZpKVa5MZI40L8',
    appId: '1:987636562974:ios:e0de66e7d2a158a900820f',
    messagingSenderId: '987636562974',
    projectId: 'indiscipleship-cb71a',
    storageBucket: 'indiscipleship-cb71a.firebasestorage.app',
    iosBundleId: 'com.example.indiscipleshipAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaoqchZaREnHPvsbbIsGZpKVa5MZI40L8',
    appId: '1:987636562974:ios:e0de66e7d2a158a900820f',
    messagingSenderId: '987636562974',
    projectId: 'indiscipleship-cb71a',
    storageBucket: 'indiscipleship-cb71a.firebasestorage.app',
    iosBundleId: 'com.example.indiscipleshipAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGtiJlqYkcIqli3NKA8HLa1s5vYTadulQ',
    appId: '1:987636562974:web:0f6acc9f60a7129000820f',
    messagingSenderId: '987636562974',
    projectId: 'indiscipleship-cb71a',
    authDomain: 'indiscipleship-cb71a.firebaseapp.com',
    storageBucket: 'indiscipleship-cb71a.firebasestorage.app',
    measurementId: 'G-W59HWGM72F',
  );
}
